### ISSUE TITLE
AnalysisException when `spark.clickhouse.write.repartitionNum` set

### ISSUE THREAD

**Issue by camper42** [ClickHouse/spark-clickhouse-connector#155]
error log:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/spark/python/pyspark/sql/readwriter.py", line 1158, in append
    self._jwriter.append()
  File "/usr/local/spark/python/lib/py4j-0.10.9.3-src.zip/py4j/java_gateway.py", line 1322, in __call__
  File "/usr/local/spark/python/pyspark/sql/utils.py", line 117, in deco
    raise converted from None
pyspark.sql.utils.AnalysisException: The number of partitions can't be specified with unspecified distribution. Invalid writer requirements detected.
```

reproduce:

1. use latest snapshot
```
pyspark --repositories https://oss.sonatype.org/content/repositories/snapshots --packages com.github.housepower:clickhouse-spark-runtime-3.2_2.12:0.4.0-SNAPSHOT
```
```
❯ md5sum com.github.housepower_clickhouse-spark-runtime-3.2_2.12-0.4.0-SNAPSHOT.jar
26642b8172159b05a7d1748dc47e764c  com.github.housepower_clickhouse-spark-runtime-3.2_2.12-0.4.0-SNAPSHOT.jar
```

3. write to clickhouse
```
df = spark.read.json("/usr/local/spark/examples/src/main/resources/people.json")
spark.sql("set spark.clickhouse.write.repartitionNum=4").show()
df.writeTo("`ck-1`.dev.error").append()
```

**Comment by pan3793** [comment]
This restriction comes from Spark, basically, when you are trying to write a DataFrame to ClickHouse, the connector analyzes the ClickHouse table schema and converts ClickHouse "sharding keys(if it is distributed table partition w/o `rand()`)" + "partition cols(if present)" to Spark catalyst partition expressions, and Spark injects such a repartition into the execution plan.

If the converted "Spark catalyst partition expressions" is empty, when you are setting `spark.clickhouse.write.repartitionNum` to a non-zero value, the error occurs.

**Comment by camper42** [comment]
So, set `spark.clickhouse.write.repartitionNum` to non-zero and `spark.clickhouse.write.repartitionByPartition` to `false` cause this problem ?

---

My original intention was to limit concurrent query to clickhouse, but it seems that the number of partitions does not determine the number of queries.

Try to inc batchSize, and concurrent query become lower (and faster)

**Comment by mzitnik** [comment]
@camper42 did it answered your question

**Comment by camper42** [comment]
> @camper42 did it answered your question

yes
