### ISSUE TITLE
Memory problem with connector version 0.5.0

### ISSUE THREAD

**Issue by zy-kkk** [ClickHouse/spark-clickhouse-connector#185]
When I followed the tutorial to download the Spark connector version 0.5.0 and the latest Clickhouse-JDBC, I used spark-SQL with grpc to read the Clickhouse data, and the following error occurred

xenon. clickhouse. except ion . CHServerException: [GRPC] default@localhost :9100}/ssb [241] DB: :Exception: Memory limit (total) exceeded: would use 64.76 GiB (attempt to allocate chunk of 34358328320 bytes), maximu55.58 GiB. OvercommitTracker decision: Query was selected to stop by OvercommitTracker.. server C lickHouseNode luri=grpc:// loca lhost : 9100/ ssb a999451279

**Comment by pan3793** [comment]
Which Spark and ClickHouse versions you are using? And is the ssb table a partitioned table? Please provide your ssb table schema and scales, and the Spark query SQL.

Basically, the connector will discover the clickhouse table's partition, and spilt the spark table scan operator into `SELECT <required_columns> FROM <clickhouse_db>.<clickhouse_tbl> WHERE _partition_id=<partition_id>` by paritions, then retrieve data in streaming mode, so it would not expected huge memory usage. Could you please try HTTP mode and see what happens?

**Comment by zy-kkk** [comment]
The Clickhouse version I tried was 22.7.2.15, My Spark version is Spark-3.2.2-bin-hadoop3.2, and my JAR versions are clickhouse-jDBC-0.3.2-Patch11-all. jar and clickhouse-spark-runtime-3.2_2.12-0.5.0.jar. When I query using HTTP, I don't have a problem, no matter how much data I query, but when I use GRPC, I also run out of memory for query volume limits. In the end I had to switch to Clickhouse-spark-runtime-3.2_2.12-0.4.0. jar, and neither HTTP nor GRPC was a problem when I used this version

**Comment by zy-kkk** [comment]
@pan3793 Hello, may I ask if this problem has been solved？

**Comment by pan3793** [comment]
Sorry, there is no further investigation.

**Comment by mzitnik** [comment]
> Sorry, there is no further investigation.
