### ISSUE TITLE
Enhance documentations code example

### ISSUE THREAD

**Issue by BentsiLeviav** [ClickHouse/spark-clickhouse-connector#353]
Currently, the repo's documentation (which is maintained both in the README file and in the ClickHouse official documentation site), contains only Spark SQL examples.
We want to enhance the code examples API to include: Scala, Java, Python (pyspark), and SQL (Spark SQL).

**Comment by BentsiLeviav** [comment]
Topics we would like to have in the documentation:
* Explaining in a nutshell about the available approaches to connect to ClickHouse with Spark (JDBC and Native connector)
* For each approach provide the following topics:
    * Quick background about the approach. 
    * Setup guide
    * Read examples (Java, Scala, Python, and SparkSQL)
    * Write examples (Java, Scala, Python, and SparkSQL)
    * DDL examples (Java, Scala, Python, and SparkSQL)
    * Compatability matrix (Spark version, JDBC/Java package version, Native connector version, CH version)
    * Type support
    * Known Limitations
    * Advanced examples, specifically around parallelism and performance tuning tips. 
* Benchmarks (future)

The structure is not yet to be closed. These are topics we would love to cover.
The community is welcome to add more topics.

**Comment by mshustov** [comment]
@BentsiLeviav, should we close the current issue once https://github.com/ClickHouse/clickhouse-docs/pull/2789 has been merged? We can create a separate issue for the future enhancements
