### ISSUE TITLE
Auto update configuration docs

### ISSUE THREAD

**Issue by pan3793** [ClickHouse/spark-clickhouse-connector#77]
Keep the configuration page consistent with `ClickHouseSQLConf`

**Comment by mzitnik** [comment]
looks like it is something that has already been implemented. Can I close it

**Comment by pan3793** [comment]
Yes, `UPDATE=1 ./gradlew test --tests=ConfigurationSuite`, the golden result file is "docs/configurations/02_sql_configurations.md".
